version: '2'
services:
  localsolver:
    image: kmence/localsolver:6.5
    command: top  
  tomcat:
    
    image: tomcat:9.0
    depends_on:
      - localsolver
    environment:
      - LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/opt/localsolver_6_5/bin
    container_name: tomcat
    ports:
     - "8080:8080"
    volumes:
     - ./tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
     - ./tomcat/conf/context.xml:/usr/local/tomcat/conf/Catalina/locahost/context.xml
     - ./tomcat/www:/usr/local/tomcat/webapps
    volumes_from:
     - localsolver
  mysql:
    image: mysql
    volumes:
     - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
